### ISSUE TITLE
munmap_chunk(): invalid pointer  Aborted (core dumped)

### ISSUE THREAD

**Issue by dbear496** [ledger/ledger#2269]
I started getting this error message while parsing my journal:
```
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
I still get the error after reducing my journal to the following tmp.dat and tmp2.dat. Reducing it further makes the error go away.

tmp.dat:
```
tag xyz
  check value =~ /abc/

include tmp2.dat

2023-04-03
  acc  $1
  acc  $-1
  ; xyz: abc
```
tmp2.dat:
```
2023-03-24
  acc  $1
  acc  $-1
  ; xyz: abc

2023-03-26
  ; uvw: def
  acc  $1
  acc  $-1
```
Running:
```
$ ledger -f tmp.dat --args-only print
munmap_chunk(): invalid pointer
Aborted (core dumped)
$ ledger --version
Ledger 3.3.2-20230330, the command-line accounting tool
...
```

**Comment by tbm** [comment]
```
0x000055555563e75f in ledger::value_t::storage_t::acquire (this=0x7f76ffff6414) at /home/tbm/tmp/src/ledger/src/value.h:196
196	      refc++;
(gdb) where
#0  0x000055555563e75f in ledger::value_t::storage_t::acquire (this=0x7f76ffff6414) at /home/tbm/tmp/src/ledger/src/value.h:196
#1  0x000055555563eb4f in ledger::intrusive_ptr_add_ref (storage_ptr=0x7f76ffff6414) at /home/tbm/tmp/src/ledger/src/value.h:207
#2  0x00005555556520a1 in boost::intrusive_ptr<ledger::value_t::storage_t>::intrusive_ptr (this=0x7fffffff6c28, rhs=...)
    at /usr/include/boost/smart_ptr/intrusive_ptr.hpp:93
#3  0x000055555564cf55 in boost::intrusive_ptr<ledger::value_t::storage_t>::operator= (this=0x7fffffff6f68, rhs=...)
    at /usr/include/boost/smart_ptr/intrusive_ptr.hpp:154
#4  0x000055555563f039 in ledger::value_t::operator= (this=0x7fffffff6f68, val=...) at /home/tbm/tmp/src/ledger/src/value.h:371
#5  0x000055555563ef94 in ledger::value_t::value_t (this=0x7fffffff6f68, val=...) at /home/tbm/tmp/src/ledger/src/value.h:366
#6  0x00007ffff79fbbf1 in ledger::value_scope_t::get_value (this=0x7fffffff6050) at /home/tbm/tmp/src/ledger/src/scope.h:589
...
```

**Comment by tbm** [comment]
related to #1800?
