### ISSUE TITLE
6 python tests failing in 3.3.0

### ISSUE THREAD

**Issue by bremner** [ledger/ledger#2302]
Ledger is currently scheduled to be removed from the next stable release of Debian due to the following failing tests in ledger 3.3.0. Full log is at [1], extract containing tests is at [2].

```
> The following tests FAILED:
> 	  3 - demo (Failed)
> 	307 - RegressTest_4D9288AE_py (Failed)
> 	344 - RegressTest_78AB4B87_py (Failed)
> 	357 - RegressTest_9188F587_py (Failed)
> 	374 - RegressTest_B21BF389_py (Failed)
> 	417 - RegressTest_xact_code_py (Failed)
> Errors while running CTest
```

[1]: http://qa-logs.debian.net/2023/10/27/ledger_3.3.0-4_unstable.log
[2]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054728

**Comment by tbm** [comment]
This is something for @afh although I'm not sure if he's around at the moment. @afh ping?

I wonder why this hasn't been flagged before. I thought GitHub CI was testing Python 3, so not sure.

**Comment by tbm** [comment]
Debian unstable has Python 3.11.4. I wonder what the GitHub CI is using...

**Comment by tbm** [comment]
Hm, possibly 3.11.5 on macOS.

@afh are you around?

**Comment by afh** [comment]
Thanks for raising this @bremner and thanks for the preliminary investigation @tbm, much appreciated.


@tbm did you have a look at a publicly available output of a test run or reproduce locally?

**Comment by tbm** [comment]
@afh I looked at the log @bremner mentioned:

http://qa-logs.debian.net/2023/10/27/ledger_3.3.0-4_unstable.log

**Comment by afh** [comment]
ℹ️ @tbm GitHub CI seems to be testing with Python 3.10.12 on `ubuntu-latest`, i.e Ubuntu 22.04 (see [runner-images](https://github.com/actions/runner-images)). According to the [full log](http://qa-logs.debian.net/2023/10/27/ledger_3.3.0-4_unstable.log) Cmake reports Python version 3.11.6 being found.

ℹ️ The [full log](http://qa-logs.debian.net/2023/10/27/ledger_3.3.0-4_unstable.log) informs _"I: NOTICE: Log filtering will replace 'build/ledger-LYcYiL/ledger-3.3.0' with '<<PKGBUILDDIR>>'"_, which seems to be a path of reasonable length.

❓ @bremner Are the test failures on Debian un/stable also observed with [ledger 3.3.2](https://github.com/ledger/ledger/releases/tag/v3.3.2)?

❓ Is it possible to get an archive of the build directory (e.g. `build/ledger-LYcYiL/ledger-3.3.0`) for closer inspection?

❓ Is a build history for ledger on Debian available from which one can see when tests started to fail and what may have changed in ledger or the test environment?

**Comment by afh** [comment]
> Yes, I just duplicated the failures with 3.3.2

😢 This might hint at an issue with the test environment. Anything Debian-specific or unusual that comes to your mind, @bremner?

> Sure, but it's likely to be pretty large (and contained dynamically
linked executables). How would you like to receive it?

Depending on the size via e-mail (< ~50MB) or a public download link from a server you have access to or a file-sharing service that does not require sign-in.

> I just have the one previous successful build of 3.3.0

🙏 Taking a look…

**Comment by bremner** [comment]
Alexis Hildebrandt ***@***.***> writes:

>> Yes, I just duplicated the failures with 3.3.2
>
> 😢 This might hint at an issue with the test environment. Anything Debian-specific or unusual that comes to your mind, @bremner?

No, this is in a current debian unstable chroot.

>> Sure, but it's likely to be pretty large (and contained dynamically
> linked executables). How would you like to receive it?
>
> Depending on the size via e-mail (< ~50MB) or a public download link from a server you have access to or a file-sharing service that does not require sign-in.

The build dir for 3.3.0 is temporarily available from

   https://people.debian.org/~bremner/ledger.tar.xz

please let me know when you have retrieved it

**Comment by afh** [comment]
Thanks, @bremner, I have retrieved it.

**Comment by afh** [comment]
After digging through Ledger's tests I've understood what parts are involved to run the tests and I assume the error may surface in the Python interface, though I'm not sure and not sure how to best verify this.

In the following snippet the filepath argument to the `ledger.read_journal` call is complete, so maybe the last character of the path is lost when handing over the path from Python to the native C++ code, e.g. in the Python wrapper for `read_journal` (see [`py_session.cc:83f`](https://github.com/ledger/ledger/blob/master/src/py_session.cc#L83-L85) and [`py_session.cc:45f`](https://github.com/ledger/ledger/blob/master/src/py_session.cc#L45-L48)).

Could the used locale (`C.UTF-8`) and its encoding affect strings in this regard? 
What could other potential causes for this issue be? Any ideas are welcome.

```
307:   +Traceback (most recent call last):
307: 
307:   +  File "/<<PKGBUILDDIR>>/test/regress/4D9288AE.py", line 3, in <module>
307: 
307:   +    for post in ledger.read_journal("test/regress/4D9288AE.dat").query("^expenses:"):
307: 
307:   +                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
307: 
307:   +RuntimeError: Cannot read journal file "/<<PKGBUILDDIR>>/test/regress/4D9288AE.da"
307: 
307:   +Error: Failed to execute Python module
```

At @bremner do you have access to a Debian Unstable system and would be able to compile ledger from source and run the following from a ledger repo clone?

`python test/RegressTests.py $PATH_TO_BUILD/ledger . ./test/regress/4D9288AE_py.test`

/cc @jwiegley

**Comment by bremner** [comment]
Alexis Hildebrandt ***@***.***> writes:

>
> At @bremner do you have access to a Debian Unstable system and would be able to compile ledger from source and run the following from a ledger repo clone?
>
> `python test/RegressTests.py $PATH_TO_BUILD/ledger . ./test/regress/4D9288AE_py.test`
>
> /cc @jwiegley

Looks quite similar (this is in a debian unstable chroot on a debian
testing system, but I would be surprised if that matters).

***@***.***:~/ledger-upstream$ python test/RegressTests.py ./ledger . ./test/regress/4D9288AE_py.test
FAILURE in output from ./test/regress/4D9288AE_py.test:
--
$ledger -f "/home/bremner/ledger-upstream/test/regress/4D9288AE_py.test" python test/regress/4D9288AE.py

--
  @@ -1 +0,0 @@

  -None

FAILURE in error output from ./test/regress/4D9288AE_py.test:
--
$ledger -f "/home/bremner/ledger-upstream/test/regress/4D9288AE_py.test" python test/regress/4D9288AE.py

--
  @@ -0,0 +1,6 @@

  +Traceback (most recent call last):

  +  File "/home/bremner/ledger-upstream/test/regress/4D9288AE.py", line 3, in <module>

  +    for post in ledger.read_journal("test/regress/4D9288AE.dat").query("^expenses:"):

  +                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  +RuntimeError: Cannot read journal file "/home/bremner/ledger-upstream/test/regress/4D9288AE.da"

  +Error: Failed to execute Python module

FAILURE in exit code (0 != 1) from ./test/regress/4D9288AE_py.test:
--
$ledger -f "/home/bremner/ledger-upstream/test/regress/4D9288AE_py.test" python test/regress/4D9288AE.py

--
E[4D9288AE_py.test]
FAILED (1)

It seems that something is unconditionally cutting off the last
character in the path name

If I run

import ledger
l=ledger.read_journal("test/regress/4D9288AE.datt")

it works fine (or whatever character I pad with).

This is all with commit 14db8c8f10377607c85a7fe449af8001a64f088e

**Comment by afh** [comment]
Thanks @bremner, that's helpful. I've installed Debian 12 (stable) in a virtual machine and am unable to reproduce the issue so far.

I'll look to switching to debian unstable tomorrow. Any other info that you could provide that could help me get an environment up and running with which the issue can be reproduced would be very much appreciated.

**Comment by afh** [comment]
After an update to Debian unstable all ledger tests continue to succeed for me and I am unable to reproduce the reported issue.

Here is how I set up my testing/debugging environment:

* Laptop runs macOS 14.1.2 on Apple-Silicon (arm64)
* Create a new virtual machine (VM) in [UTM](https://getutm.app) (Virtualize not Emulate and not using Apple Virtualization)
* Boot the VM from [debian-12.2.0-arm64-netinst.iso](https://cdimage.debian.org/debian-cd/current/arm64/iso-cd/debian-12.2.0-arm64-netinst.iso) (downloaded using [`aria2c`](https://aria2.github.io))
* Choose default simple setup, i.e. single disk, single partition, no LVM (16GB)
* [Point apt sources to unstable](https://wiki.debian.org/DebianUnstable)
```sh
sudo sed -i'' -e 's/bookworm /unstable /g' /etc/apt/sources.list
```
* Upgrade to Debian Unstable
```sh
sudo apt update && sudo apt -y full-upgrade
```
full-upgrade ran into errors while processing linux-image-6.5.0-5-arm64 and linux-image-arm64
* Reboot
* Install ledger dependencies:
```
sudo apt-get -y install git g++ cmake boost1.74 libmpfr-dev libgmp-dev libicu-dev
```
* Clone ledger repository
```sh
git clone https://github.com/ledger/ledger.git
```
* Change working directory to local ledger clone
```sh
cd ledger
```
* Configure build
```sh
cmake -Bbuild -S. -DUSE_PYTHON:BOOL=ON
```
* Build ledger
```sh
make -j4 -Cbuild
```
* Run tests
```sh
make -j4 -Cbuild test
…
100% tests passed, 0 tests failed out of 424
```
* Run exemplary failing test:
```sh
python3 test/RegressTests.py -l ./build/ledger -s . ./test/regress/4D9288AE_py.test
.
OK (1)
```
>[!NOTE]
> The latest changes on ledger `master` branch changed the test scripts (inlcuding `RegressTests.py`) to use command-line options (`-l` and `-s`) instead of positional arguments to align with the `CheckManpage.py` and `CheckTexinfo.py` scripts. To test using a previous versions of ledgers test suite run python3 test/RegressTests.py ./build/ledger . ./test/regress/4D9288AE_py.test

@bremner How does the above setup differ from your or the Debian testing chroot setup and how can I mimick it?

**Comment by afh** [comment]
ℹ️ Tested with `clang` instead of `g++` and got the same results as above ☝️

**Comment by jwiegley** [comment]
My output is:
```
ledger-py3:[johnw@Vulcan:~/src/ledger/master]$ python3 test/RegressTests.py ~/Products/master/debug/ledger . ./test/regress/4D9288AE_py.test
FAILURE in output from ./test/regress/4D9288AE_py.test:
--
$ledger -f "/Users/johnw/src/ledger/master/test/regress/4D9288AE_py.test" python test/regress/4D9288AE.py

--
  @@ -1 +0,0 @@

  -None

FAILURE in error output from ./test/regress/4D9288AE_py.test:
--
$ledger -f "/Users/johnw/src/ledger/master/test/regress/4D9288AE_py.test" python test/regress/4D9288AE.py

--
  @@ -0,0 +1 @@

  +Error: Unrecognized command 'python'

FAILURE in exit code (0 != 1) from ./test/regress/4D9288AE_py.test:
--
$ledger -f "/Users/johnw/src/ledger/master/test/regress/4D9288AE_py.test" python test/regress/4D9288AE.py

--
E[4D9288AE_py.test]
FAILED (1)

```

**Comment by bremner** [comment]
David Bremner ***@***.***> writes:


> I don't know if it is significant, but that uses libutfcpp 3.2.5 from
> Debian. That _seems_ to be more recent (Sept 2023) than the embedded version, but I
> did not verify the hash.

I just confirmed that "apt install libtutfcpp-dev" on top of the
dependencies you mentioned triggers that failures. So it seems ledger is
incompatible with newer utfcpp?

d

**Comment by afh** [comment]
Thanks for confirming, @bremner. I am now able to reproduce the issue in my Debian unstable VM 🎉

I'll have a closer look at newer versions of [utfcpp](https://github.com/nemtrif/utfcpp) and what changed between them. Ledger contains the [3.2.2 source](https://github.com/ledger/ledger/tree/master/lib/utfcpp/v3), Debian unstable offers [3.2.5](https://packages.debian.org/sid/libutfcpp-dev) and the latest release is [4.0.3](https://github.com/nemtrif/utfcpp/releases/tag/v4.0.3).

---

Off-topic: In case it has slipped your attention I'd appreciate your thoughts on #2313, which adds support for installing Debian Trixie dependencies via ledger's `acprep`.
Apologies for this nudge if you did see the message and did not get to it yet or decided to not comment.

**Comment by bremner** [comment]
Alexis Hildebrandt ***@***.***> writes:

> If I've tested properly the issue first appears when using utfcpp [v3.2.5](https://github.com/nemtrif/utfcpp/releases/tag/v3.2.5) and disappears again when using utfcpp [v4.0.1](https://github.com/nemtrif/utfcpp/releases/tag/v4.0.1).
>
> * Can debian update utfcpp to at least 4.0.1? Will this be enough for current stable and testing?
> * Can we find a quick and maintainable fix?
> * Should ledger drop support for third-party packaged utfcpp and simply maintain its own version from here on?
>

Updating utfcpp in debian should be doable. There might be a slight gap
where ledger gets dropped from testing, but it will be fine with respect
to the next stable release. I will ask the utfcpp maintainer to upgrade [1].

I hope that ledger continues to support third party utfcpp, although
since it's a header only library, the arguments against embedding are
somewhat less compelling.


[1]: you can follow the upgrade discussion at
     https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057732

**Comment by afh** [comment]
That's good news, @bremner and thanks for asking the Debian maintainer of utfcpp. Any specific reason why the request is to update utfcpp in Debian to 4.0.1 instead of the current latest version 4.0.3?

Your voice is appreciated and heard regarding ledger supporting third-party utfcpp. Just to understand the motivation for not embedding, what are the benefits from a distribution's point of view?

ℹ️ Checking the utfcpp [release notes](https://github.com/nemtrif/utfcpp/releases) the following two issues are mentioned and seem related to the observed misbehaviour:

* [nemtrif/utfcpp#111](https://github.com/nemtrif/utfcpp/issues/111)
* [nemtrif/utfcpp#78](https://github.com/nemtrif/utfcpp/issues/78)

**Comment by afh** [comment]
The author of [nemtrif/utfcpp](https://github.com/nemtrif/utfcpp) suggests:
> Instead of using `utf8::unchecked::utf16to8()`, use `utf8::utf16to8()`. It is safer anyway and just a bit slower.

@jwiegley what was the initial motivation for using the unchecked variant?

**Comment by bremner** [comment]
Alexis Hildebrandt ***@***.***> writes:

> That's good news, @bremner and thanks for asking the Debian maintainer of utfcpp. Any specific reason why the request is to update utfcpp in Debian to 4.0.1 instead of the current latest version 4.0.3?

I just read that 4.0.1 fixed it, missed that newer ones were
available. I've updated the Debian bug.

>
> Your voice is appreciated and heard regarding ledger supporting
> third-party utfcpp. Just to understand the motivation for not
> embedding, what are the benefits from a distribution's point of view?

It makes it easier for distros to deal with security issues, since only
a rebuild against the fixed library (in this case utfcpp) is needed,
rather than a new release or patching of the client package (in this
case ledger).

d

**Comment by hosiet** [comment]
Debian utfcpp packager here. While the best way might be upgrading Debian's utfcpp to 4.0.x, some other Debian's software will encounter build failures when using utfcpp 4.0.x so that won't happen immediately.

I plan to downgrade Debian's utfcpp to 3.2.4 for now, and later eventually upgrade Debian's utfcpp to 4.x series when all software are compatible with utfcpp 4.0.x. I believe further coordination is definitely needed; just let me know if I can further help.

**Comment by hosiet** [comment]
Thanks. The downgrade to utfcpp 3.2.4 has now happened. For more information, please see https://tracker.debian.org/pkg/utfcpp .

**Comment by afh** [comment]
That's great to hear, @hosiet. Thanks for moving so quickly on this and raising awareness for the issue with apertium.

**Comment by afh** [comment]
@bremner thanks for the context on why distros prefer programs to link to libutfcpp, that makes a lot of sense.

A few things that are on my mind:

1. Where can I follow Debian ledger builds with the downgraded utfcpp?
2. What needs to happen, so that the Debian bug [#1054728](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054728) and this bug can be closed?
3. Are there plans to update Debian ledger to 3.3.2?
4. Is there anything else that is open and that I could help with?

**Comment by bremner** [comment]
Alexis Hildebrandt ***@***.***> writes:

> A few things that are on my mind:
> 1. Where can I follow Debian ledger builds with the downgraded utfcpp?

https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/ledger.html

I didn't figure out how to trigger rebuilds, I guess they should happen eventually.

> 2. What needs to happen, so that the Debian bug
> [#1054728](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054728)
> and this bug can be closed?

I (just) closed this bug based on a local rebuild.

> 3. Are there plans to update Debian ledger to 3.3.2?

Yes, I just did that; I was waiting for the situation with 3.3.0 to
clarify.

> 4. Is there anything else that is open and that I could help with?

I should really create an github issue for 

  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1039736

I haven't had a chance to check the existing issues for duplication.

**Comment by tbm** [comment]
>   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1039736
> I haven't had a chance to check the existing issues for duplication.

There are many open bugs about `print` dropping information and creating invalid syntax. I'll check tomorrow if one matches the Debian report (#1768 is very close).

**Comment by jwiegley** [comment]
> The author of [nemtrif/utfcpp](https://github.com/nemtrif/utfcpp) suggests:
> 
> > Instead of using `utf8::unchecked::utf16to8()`, use `utf8::utf16to8()`. It is safer anyway and just a bit slower.
> 
> @jwiegley what was the initial motivation for using the unchecked variant?

I really don't remember, maybe just speed.
