### ISSUE TITLE
Assertion failure when using both --unround and --group-by account

### ISSUE THREAD

**Issue by cpitclaudel** [ledger/ledger#518]
Assume `test.ledger` contains this:

```
2017-12-23 a
    Expenses:A  $1
    Assets

2017-12-25 b
    Expenses:B  $1
    Assets
```

Then running `ledger -f test.ledger reg --group-by account --unround` prints that:

```
terminate called after throwing an instance of 'ledger::assertion_failed'
  what():  Assertion failed in "/build/ledger-2L3TES/ledger-3.1.1+dfsg1/src/op.h", line 259:void ledger::expr_t::op_t::release() const: refc > 0
Aborted
```

**Comment by jwiegley** [comment]
In case you didn't already know, if you build with debugging enabled (passing `-DBUILD_DEBUG=1` to `cmake`), then the following becomes available:

  ledger --debug 'calc.expr' <command>

Which will show you what Ledger is thinking when it evaluates expressions.  The argument to `--debug` is a regexp matching one of many debug patterns throughout the code.

**Comment by mbudde** [comment]
It looks like ledger ends up in some kind of infinite loop where a refcount keeps getting incremented until it overflows. It could look like a scope ends up pointing to itself. Any ideas for how this could happen?
```
[...]
33961ms  [DEBUG]
33961ms  [DEBUG] .
33961ms  [DEBUG] ..
33961ms  [DEBUG] Binding scope 0x7ffd894f8dc0 with 0x192b2f0
33961ms  [DEBUG] ...
33961ms  [DEBUG] ....
33962ms  [DEBUG] .....
33962ms  [DEBUG] Binding scope 0x19315e0 with 0x192b110
33962ms  [DEBUG] ......
33962ms  [DEBUG] Lookup: amount in 0x1931620
33962ms  [DEBUG] Acquiring 0x192b2a0, refc now 1
33962ms  [DEBUG] Found definition:
0x192b2a0         FUNCTION (1)
33962ms  [DEBUG] Acquiring 0x192b2a0, refc now 2
33962ms  [DEBUG] Acquiring 0x192b2a0, refc now 3
33962ms  [DEBUG] Acquiring 0x1930c40, refc now 1
33962ms  [DEBUG] Acquiring 0x192b2a0, refc now 4
33962ms  [DEBUG] Releasing 0x192b2a0, refc now 3
33962ms  [DEBUG] Releasing 0x192b2a0, refc now 2
33962ms  [DEBUG] Releasing 0x192b2a0, refc now 1
33962ms  [DEBUG] ......
33962ms  [DEBUG] Acquiring 0x1930c40, refc now 2
33962ms  [DEBUG] Acquiring 0x1930c40, refc now 3
33962ms  [DEBUG] Acquiring 0x192c9a0, refc now 1
33962ms  [DEBUG] Acquiring 0x1930c40, refc now 4
33962ms  [DEBUG] Releasing 0x1930c40, refc now 3
33962ms  [DEBUG] Releasing 0x1930c40, refc now 2
33962ms  [DEBUG] Acquiring 0x192c9a0, refc now 2
33962ms  [DEBUG] Releasing 0x192c9a0, refc now 1
33962ms  [DEBUG] Releasing 0x1930c40, refc now 1
33962ms  [DEBUG] .....
33962ms  [DEBUG] Defining amount_expr in 0x19315e0
33962ms  [DEBUG] Acquiring 0x192c9a0, refc now 2
33962ms  [DEBUG] Acquiring 0x192c9a0, refc now 3
33962ms  [DEBUG] Acquiring 0x192c9a0, refc now 4
[... Keeps incrementing until refc overflows:]
193401ms  [DEBUG] Acquiring 0x192c9a0, refc now 32765
193401ms  [DEBUG] Acquiring 0x192c9a0, refc now 32766
193401ms  [DEBUG] Acquiring 0x192c9a0, refc now 32767
193401ms  [DEBUG] Acquiring 0x192c9a0, refc now 32768
193401ms  [DEBUG] Acquiring 0x192c9a0, refc now -32767
193418ms  [DEBUG] Releasing 0x192c9a0, refc now -32769
terminate called after throwing an instance of 'ledger::assertion_failed'
  what():  Assertion failed in "./src/op.h", line 259
:void ledger::expr_t::op_t::release() const: refc > 0
```
```
(gdb) bt
#0  ledger::expr_t::op_t::acquire (this=0x7ea870) at ./src/op.h:253
#1  0x00007ffff78a3fd2 in ledger::intrusive_ptr_add_ref (op=0x7ea870)
    at ./src/op.cc:43
#2  0x00000000004fbfcb in boost::intrusive_ptr<ledger::expr_t::op_t>::intrusive_ptr (this=0x7ffffffe7500,
    rhs=...) at /usr/include/boost/smart_ptr/intrusive_ptr.hpp:92
#3  0x00000000004fac20 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#4  0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#5  0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#6  0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#7  0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#8  0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#9  0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#10 0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189

[...]

#100 0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7fffffffcac0, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#101 0x00000000004fac38 in ledger::bind_scope_t::define (this=0x7e5b30, kind=ledger::symbol_t::FUNCTION,
    name="amount_expr", def=...) at ./src/scope.h:189
#102 0x00007ffff78a4f28 in ledger::expr_t::op_t::compile (this=0x7ea5d0, scope=..., depth=4, param_scope=0x0)
    at ./src/op.cc:148
#103 0x00007ffff78a57fb in ledger::expr_t::op_t::compile (this=0x7e6b30, scope=..., depth=3, param_scope=0x0)
    at ./src/op.cc:204
#104 0x00007ffff78a57fb in ledger::expr_t::op_t::compile (this=0x7eacb0, scope=..., depth=2, param_scope=0x0)
    at ./src/op.cc:204
#105 0x00007ffff78a4e2b in ledger::expr_t::op_t::compile (this=0x7e67b0, scope=..., depth=1, param_scope=0x0)
    at ./src/op.cc:144
#106 0x00007ffff78a57fb in ledger::expr_t::op_t::compile (this=0x7ea7d0, scope=..., depth=0, param_scope=0x0)
    at ./src/op.cc:204
#107 0x00007ffff789f970 in ledger::expr_t::compile (this=0x7d4c88, scope=...)
    at ./src/expr.cc:122
#108 0x00007ffff78a1789 in ledger::merged_expr_t::compile (this=0x7d4c88, scope=...)
    at ./src/expr.cc:257
#109 0x00007ffff773e964 in ledger::expr_base_t<ledger::value_t>::calc (this=0x7d4c88, scope=...)
    at ./src/exprbase.h:167
#110 0x00007ffff787c23b in ledger::post_t::add_to_value (this=0x7ddbb0, value=..., expr=...)
    at ./src/post.cc:636
#111 0x00007ffff778a68d in ledger::calc_posts::operator() (this=0x7db310, post=...)
    at ./src/filters.cc:318
#112 0x00007ffff77883cd in ledger::post_splitter::flush (this=0x7da890)
    at ./src/filters.cc:58
#113 0x00007ffff771dcab in ledger::item_handler<ledger::post_t>::flush (this=0x7fffffffce70)
    at ./src/chain.h:76
#114 0x00007ffff77d16e2 in ledger::pass_down_posts<ledger::journal_posts_iterator>::pass_down_posts (
    this=0x7fffffffce70, handler=..., iter=...) at ./src/filters.h:168
#115 0x00007ffff77b4467 in ledger::report_t::posts_report (this=0x7d4a00, handler=...)
    at ./src/report.cc:359
#116 0x00007ffff77de5eb in ledger::reporter<ledger::post_t, boost::shared_ptr<ledger::item_handler<ledger::post_t> >, &ledger::report_t::posts_report>::operator() (this=0x7dafe0, args=...)
    at ./src/report.h:1089
#117 0x00007ffff77dc797 in boost::detail::function::function_obj_invoker1<ledger::reporter<ledger::post_t, boost
::shared_ptr<ledger::item_handler<ledger::post_t> >, &ledger::report_t::posts_report>, ledger::value_t, ledger::
call_scope_t&>::invoke (function_obj_ptr=..., a0=...) at /usr/include/boost/function/function_template.hpp:138
#118 0x000000000053196f in boost::function1<ledger::value_t, ledger::call_scope_t&>::operator() (
    this=0x7fffffffd0a0, a0=...) at /usr/include/boost/function/function_template.hpp:773
#119 0x000000000051b793 in ledger::global_scope_t::execute_command (this=0x7d07a0, args=..., at_repl=false)
    at ./src/global.cc:261
#120 0x000000000051ba14 in ledger::global_scope_t::execute_command_wrapper (this=0x7d07a0, args=...,
    at_repl=false) at ./src/global.cc:271
#121 0x00000000004f80d2 in main (argc=8, argv=0x7fffffffdcd8, envp=0x7fffffffdd20)
    at ./src/main.cc:121
```

**Comment by jwiegley** [comment]
I'm not sure off the top of my head how it could happen, but I think you've correctly diagnosed the root cause. I've seen this before, though it was long ago.
